# Generated by Django 4.2.5 on 2023-12-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quote',
        ),
    ]
